data:
  data_path: "data/data_ner_updated.json"
  train_path: "data/train_data.json"
  test_path: "data/test_data.json"
  test_size: 0.2
  random_state: 42
  max_length: 128
  label_list:
    - "O"
    - "B-Name"
    - "I-Name"
    - "B-Position"
    - "I-Position"
    - "B-Company"
    - "I-Company"
    - "B-Address"
    - "I-Address"
    - "B-Phone"
    - "I-Phone"
    - "B-Email"
    - "I-Email"
    - "B-Department"
    - "I-Department"
model:
  model_checkpoint: "Davlan/xlm-roberta-base-ner-hrl"
train:
  output_dir: "./ner_output"
  logging_dir: "./logs_output"
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
  save_strategy: "epoch"
  evaluation_strategy: "epoch"
  learning_rate: 2e-5
  per_device_train_batch_size: 8
  num_train_epochs: 10
  weight_decay: 0.01
  logging_steps: 10
  logging_strategy: "epoch"
  report_to: "none"
  fp16: true
  optim: "adamw_torch"
  load_best_model_at_end: true
  metric_for_best_model: "accuracy"
  greater_is_better: true
  save_total_limit: 1
eval:
  per_device_eval_batch_size: 8
augment:
  enabled: true       
  type: "space_newline"
  prob_space: 0.9
  prob_newline: 0.5
  max_spaces: 8         
